sudo: required
language: node_js
node_js:
  - '8.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm i --silent --no-optional -g angular-cli-ghpages

script:
  - karma start karma.conf.js --single-run
  - ng build --prod --base-href "$BASE_HREF" --verbose
  - npm run copy-readme
  - angular-cli-ghpages --repo=https://$GH_TOKEN@github.com/oskar1233/awg-blog.git --name="oskar1233" --email=ooskar1233@yahoo.com --branch=gh-pages
